### ISSUE TITLE
addon TranqRotation zhCN Client error

### ISSUE THREAD

**Issue by Qcat0214** [Road-block/Select_AddOns#1]
hi block.
This addon is very good for hunters. I've localize it
But in Chinese client. It can't send raid chat messages.
Press "Next Hunter"Button."Sync"Button."Skip"Button. and "Restart" Button all will be error.
The following are:
Addon\TranqRotation\TranqRotation.lua:206: Unknown addon chat type
Addon\TranqRotation\TranqRotation.lua:190: Unknown addon chat type
Addon\TranqRotation\TranqRotation.lua:217: Unknown addon chat type
Addon\TranqRotation\TranqRotation.lua:182: Unknown addon chat type

**Comment by Road-block** [comment]
I know what's the problem with this one I'll push an update in a few minutes.

**Comment by Road-block** [comment]
Can you attach your localization here so I include it in the new package?

**Comment by Qcat0214** [comment]
ok!

TQ_MSG_ORDER      = "<宁神循环> 循环顺序: ";
TQ_MSG_TRANQED    = "宁神完毕";
TQ_MSG_TRANQMISS  = "的宁神没有击中";
TQ_MSG_TRANQFAIL  = "的宁神施放失败,目标:";
TQ_MSG_SHOTNAME   = "宁神射击";
TQ_MSG_SELFCAST   = "你对(.+)施放了"..TQ_MSG_SHOTNAME.."。";
TQ_MSG_SHOTFAIL   = "你未能驱散(.+)的疯狂。"
TQ_MSG_FRENZY1    = "goes into a killing frenzy!";
TQ_MSG_FRENZY2    = "goes into a frenzy!";
TQ_MSG_TRANQ_NOW  = ", 宁神射击!";
TQ_MSG_TRANQ_NEXT = ", 你是下个宁神.";
TQ_MSG_SKIP       = " 现在不能宁神, 跳过!";
TQ_MSG_SKIPPATT   = TQ_MSG_SKIP.." : (.+).";
TQ_MSG_RESTART    = " 请求宁神重新开始循环.";
TQ_MSG_SYNCREQ    = " 请求宁神同步循环.";
TQ_MSG_SYNCMSG    = " 准备下一个宁神,等 ";
TQ_MSG_SYNCPATT   = "(.+)"..TQ_MSG_SYNCMSG.."(.+)放完.";
TQ_MSG_SYNCRECV   = " 同步版本 ";
TQ_MSG_SYNCRCVPT  = "(.+)"..TQ_MSG_SYNCRECV.."(.+)"
TQ_MSG_DELIMITER  = " => ";
TQ_MSG_TIMESTOP   = "时间停止";
TQ_MSG_GETTS      = "你受到了"..TQ_MSG_TIMESTOP.."效果的影响。";
TQ_MSG_LOSTTS     = TQ_MSG_TIMESTOP.."效果从你身上消失了。";

TQ_MSG_CAPTAIN    = "队长循环模式";
TQ_MSG_STATUS     = "显示状态窗口";
TQ_MSG_HUNTER1    = "第一猎人宁神循环";
TQ_MSG_HUNTER2    = "第二猎人宁神循环";
TQ_MSG_HUNTER3    = "第三猎人宁神循环";
TQ_MSG_HUNTER4    = "第四猎人宁神循环";
TQ_MSG_HUNTER5    = "第五猎人宁神循环";
TQ_MSG_HUNTER6    = "第六猎人宁神循环";

TQ_MSG_CHANNEL    = "团队";

TQ_MSG_FEAR       = "恐惧";
TQ_MSG_PANIC      = "恐慌";
TQ_MSG_TIMELAPSE  = "时间流逝";
TQ_MSG_TIMESTOP   = "时间停止";
TQ_MSG_WSTING     = "翼龙钉刺";
TQ_MSG_MINDFLAY   = "精神鞭笞";
TQ_MSG_CAUSEINS   = "导致疯狂";

**Comment by Qcat0214** [comment]
TQ_MSG_FEAR = "恐惧";
I have a little doubt about this one.I'm not sure my translation is right
Because there is a space in enUS

**Comment by Road-block** [comment]
[TranqRotation211-rb.zip](https://github.com/Road-block/Select_AddOns/raw/master/TranqRotation211-rb.zip)
