### ISSUE TITLE
TranqRotation new error

### ISSUE THREAD

**Issue by Qcat0214** [Road-block/Select_AddOns#2]
First of all, thank you!It can be used normally.
Now, I press "Sync" to have a new mistake

`[2018/02/23` 21:06:00-11-x5]: TranqRotation\TranqRotation.lua:595: bad argument #1 to `lower' (string expected, got nil)
<in C code>: in function `lower'
TranqRotation\TranqRotation.lua:595: in function `IdentifyHunter'
TranqRotation\TranqRotation.lua:569: in function `TranqRotation_OnEvent'
<string>:"TranqRotationFrame:OnEvent":2: in main chunk`

**Comment by Road-block** [comment]
Have you actually set any hunters in options?  
`/tq`

**Comment by Qcat0214** [comment]
ya.yes, of course
http://i1.fuimg.com/609861/e9134e13b0630fee.png

**Comment by Road-block** [comment]
This pattern is wrong then most probably.
`TQ_MSG_SYNCPATT = "(.+)"..TQ_MSG_SYNCMSG.."(.+)放完.";`

**Comment by Road-block** [comment]
I'm trying to get a Chinese client installed because patterns like this or loot patters for XLootMonitor are impossible to debug on an English client.  
If the Chinese globalstrings have tokens in a different order then string captures will not work as expected.  
The same is true for some ruRU patterns and I have no way to fix that stuff on my end.

**Comment by Qcat0214** [comment]
oh.!!!You said it right.
Thank you very much! Solve the problem

**Comment by Road-block** [comment]
What is the correct pattern?

**Comment by Qcat0214** [comment]
No editors are needed.
just "(.+)"..TQ_MSG_SYNCMSG.."(.+)." it's ok

**Comment by Qcat0214** [comment]
I think you are right,There are many globalstrings character string in Chinese client that are different from English client.This problem is often encountered when I localize the addon.
